### ISSUE TITLE
Deploy fails in Python 3 Environment

### ISSUE THREAD

**Issue by mmobarak** [dzimine/greengo#25]
Please see this PR: https://github.com/dzimine/greengo/pull/24

Basically, there is a floating point calculation inside a `range()` in the implementation of deploy.

**Comment by dzimine** [comment]
Thanks for the report and the fix! 
We need to add python3 to .travis.yml https://github.com/dzimine/greengo/blob/master/.travis.yml and run the local python3 tests, too.
PR welcome, or I'll get to it at some point.

**Comment by dzimine** [comment]
Done for v2 branch. https://github.com/dzimine/greengo/pull/26

**Comment by dzimine** [comment]
Done for master: https://github.com/dzimine/greengo/pull/27
Now python3 is truly supported.
